version = "1.0"
#name = "Paperless-ngx configuration panel"

[main]
name = "Paperless-ngx configuration"

	[main.ocr]
	name = "Set OCR languages"
	services = ["__APP__", "__APP__-consumer","__APP__-scheduler","__APP__-task-queue"]

		[main.ocr.ocr_language]
		ask = "Which OCR languages should be perfomed on your documents"
		type = "string"
		default = "eng"
		help = """\
Read this informations: https://github.com/YunoHost-Apps/paperless-ngx_ynh/tree/master/doc/PRE_INSTALL.md\n\
If your language contains a '-' such as chi-sim, you must use chi_sim\n\
Examples:\n- eng\n- eng+fra\n- eng+fra+chi_sim"""
		bind = "PAPERLESS_OCR_LANGUAGE:__INSTALL_DIR__/main/paperless.conf"
